# Generated by Django 5.2.7 on 2025-11-01 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('data_inclusao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Marca',
                'verbose_name_plural': 'Marcas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('letra', models.CharField(max_length=1, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=200, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['letra'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo_registro', models.CharField(max_length=50, unique=True)),
                ('codigo_barras', models.CharField(max_length=13, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('custo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('informacoes_adicionais', models.TextField(blank=True, null=True)),
                ('em_promocao', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='app.categoria')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='app.marca')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-data_cadastro'],
            },
        ),
        migrations.CreateModel(
            name='Escaninho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('quantidade', models.IntegerField(default=0)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escaninhos', to='app.produto')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escaninhos', to='app.setor')),
            ],
            options={
                'verbose_name': 'Escaninho',
                'verbose_name_plural': 'Escaninhos',
                'ordering': ['setor', 'codigo'],
                'unique_together': {('setor', 'codigo')},
            },
        ),
    ]
